'use client';
import { useState } from 'react';
import { formatZAR, type PersonalLoanApplication } from '@xtra/shared';
import { Alert, Button, Field, Loading, Modal, PageHeader, StatusBadge, Table, Textarea, useApi, useAuth } from '@xtra/ui';
export default function LenderApplications() {
  const { client } = useAuth(), applications = useApi(c => c.lender.personalApplications());
  const [selected, setSelected] = useState<PersonalLoanApplication | null>(null), [notes, setNotes] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  async function review(action: 'REVIEW' | 'DECLINE') { if (!selected) return; setBusy(true); setError(null); try { await client.request('POST', `/personal-loans/applications/${selected.id}/review`, { action, notes }); applications.reload(); setSelected(null); } catch (e) { setError(e instanceof Error ? e.message : 'Could not record review'); } finally { setBusy(false); } }
  return <div className="space-y-5"><PageHeader title="Personal-loan applications" subtitle="Requests sent to your stall after platform identity and address review. Latest 100." /><Alert tone="blue">Income and expenses are applicant declarations. Verify affordability, supporting financial information and final credit terms before making a lending decision. This inbox records reviews and declines; it does not approve or pay out loans.</Alert>{applications.error && <Alert tone="red">{applications.error}</Alert>}{applications.loading ? <Loading /> : <Table rows={applications.data ?? []} empty="No applications sent to your stall yet" columns={[
    { header: 'Applicant', cell: a => `${a.firstName} ${a.lastName}` }, { header: 'Request', cell: a => <div>{formatZAR(a.amountCents)} · {a.termMonths} months<div className="text-xs text-muted">{a.purpose}</div></div> }, { header: 'Declared income / expenses', cell: a => `${formatZAR(a.monthlyIncomeCents)} / ${formatZAR(a.monthlyExpensesCents)}` }, { header: 'Status', cell: a => <StatusBadge status={a.status} /> }, { header: 'Review', cell: a => <Button size="sm" variant="secondary" disabled={a.status === 'DECLINED'} onClick={() => { setSelected(a); setNotes(a.reviewNotes ?? ''); setError(null); }}>Review</Button> },
  ]} />}<Modal open={!!selected} onClose={() => !busy && setSelected(null)} title="Review personal-loan request"><Field label="Update for the applicant"><Textarea value={notes} maxLength={500} onChange={e => setNotes(e.target.value)} /></Field>{error && <Alert tone="red">{error}</Alert>}<div className="mt-4 flex gap-2"><Button variant="danger" disabled={notes.trim().length < 3} loading={busy} onClick={() => review('DECLINE')}>Decline request</Button><Button disabled={notes.trim().length < 3} loading={busy} onClick={() => review('REVIEW')}>Mark under review</Button></div></Modal></div>;
}
