'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { parseSaId } from '@xtra/shared';
import { Alert, Button, Card, Field, Input, Select, useApi, useAuth } from '@xtra/ui';
import { homeFor } from '@/lib/config';
type Configuration = { google: boolean; apple: boolean; whatsapp: boolean; identity: boolean };
export function QuickRegistration({ accountType }: { accountType: 'CONSUMER' | 'LENDER' | 'AFFILIATE' }) {
  const { client, refreshMe } = useAuth(), router = useRouter();
  const config = useApi(c => c.request<Configuration>('GET', '/auth/passwordless/configuration'));
  const [step, setStep] = useState(0), [identityType, setType] = useState<'ID' | 'PASSPORT'>('ID'), [identityNumber, setNumber] = useState(''), [mobile, setMobile] = useState(''), [consent, setConsent] = useState(false), [code, setCode] = useState(''), [challengeId, setChallenge] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const payload = { identityType, identityNumber, accountType, consent };
  function advance() { if (identityType === 'ID' ? !parseSaId(identityNumber).valid : !/^[A-Z0-9]{6,20}$/.test(identityNumber)) { setError('Check your ID or passport number.'); return; } setError(null); setStep(1); }
  async function social(provider: 'google' | 'apple') { setBusy(true); setError(null); try { const r = await client.request<{ url: string; state: string; binding: string }>('POST', '/auth/passwordless/social/start', { ...payload, provider }); sessionStorage.setItem('xtra-sign-in-' + r.state, r.binding); window.location.assign(r.url); } catch (e) { setError(e instanceof Error ? e.message : 'Could not start sign-in'); setBusy(false); } }
  async function otp() { setBusy(true); setError(null); try { const r = await client.request<{ challengeId: string }>('POST', '/auth/passwordless/whatsapp/send', { ...payload, mobile: mobile.replace(/\s/g, '') }); setChallenge(r.challengeId); setStep(3); } catch (e) { setError(e instanceof Error ? e.message : 'Could not send code'); } finally { setBusy(false); } }
  async function verify() { setBusy(true); setError(null); try { await client.auth.verifyWhatsApp({ challengeId, code }); const me = await refreshMe(); if (me) router.replace(homeFor(me)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not verify code'); } finally { setBusy(false); } }
  const connected = config.data && (config.data.google || config.data.apple || config.data.whatsapp);
  return <Card className="mb-5 border-brand/20 bg-brand-soft/30"><h2 className="text-lg font-bold">Quick registration · start with your ID</h2><p className="mt-2 text-sm text-muted">A guided conversation, without sending your document number to an AI model. Your name and surname follow on your first visit.</p>{!connected && <div className="mt-3"><Alert tone="blue">Google, Apple and WhatsApp connections are being prepared. These methods are unavailable until connected. Use the current account form below meanwhile.</Alert></div>}
    <div className="mt-4 space-y-4">{step === 0 ? <><p className="font-semibold">What is your ID or passport number?</p><Field label="Document type"><Select value={identityType} onChange={e => { setType(e.target.value as 'ID' | 'PASSPORT'); setNumber(''); }}><option value="ID">South African ID</option><option value="PASSPORT">Passport</option></Select></Field><Field label={identityType === 'ID' ? 'ID number' : 'Passport number'}><Input value={identityNumber} maxLength={20} autoComplete="off" onChange={e => setNumber(e.target.value.replace(/\s/g, '').toUpperCase())} /></Field><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /><span>I agree to the Terms of Use and consent to processing my identity number to create this account and verify my identity.</span></label><Button disabled={!consent} onClick={advance}>Continue</Button></> : step === 1 ? <><p className="font-semibold">How would you like to sign in?</p><div className="flex flex-wrap gap-2"><Button disabled={!config.data?.google} loading={busy} onClick={() => social('google')}>Continue with Google</Button><Button disabled={!config.data?.apple} loading={busy} onClick={() => social('apple')}>Continue with Apple</Button><Button variant="secondary" disabled={!config.data?.whatsapp || busy} onClick={() => setStep(2)}>Use mobile & WhatsApp</Button></div><p className="text-xs text-muted">Disabled methods need a provider connection. A valid document format is not completed identity verification.</p><Button size="sm" variant="ghost" disabled={busy} onClick={() => setStep(0)}>Change document</Button></> : step === 2 ? <><Field label="Mobile number" hint="We will send a six-digit code to this number via WhatsApp."><Input type="tel" autoComplete="tel" value={mobile} onChange={e => setMobile(e.target.value)} /></Field><Button loading={busy} onClick={otp}>Send WhatsApp code</Button></> : <><Field label="WhatsApp verification code" hint="The code expires after five minutes and allows five attempts."><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e => setCode(e.target.value.replace(/\D/g, ''))} /></Field><Button loading={busy} disabled={code.length !== 6} onClick={verify}>Verify and continue</Button><Button variant="ghost" disabled={busy} onClick={() => setStep(2)}>Request a new code</Button></>}{error && <Alert tone="red">{error}</Alert>}</div>
  </Card>;
}
