'use client';
import { Button } from '@xtra/ui';
import { formatZAR } from '@xtra/shared';
export function SavedLoanDetails({ request, name, identity, status, province, mobile, address, income, expenses, date, reuse, setReuse, financialCurrent, setFinancialCurrent, onContinue }: {
  request?: string;
  name: string; identity: string; status: string; province: string; mobile: string; address: string; income: number | null; expenses: number | null; date: string | null;
  reuse: boolean; setReuse: (v: boolean) => void; financialCurrent: boolean; setFinancialCurrent: (v: boolean) => void; onContinue: () => void;
}) {
  const finances = income !== null && expenses !== null;
  return <div className="space-y-5"><p className="text-xs font-bold uppercase tracking-widest text-brand">Your details, already here</p><h2 className="text-2xl font-bold">Confirm once. Skip the repetition.</h2><p className="text-sm text-muted">We reuse your saved answers across XTRA-CASH. Saving a detail does not mean it has been verified.</p>{request && <p className="rounded-xl bg-brand-soft p-3 text-sm font-semibold">Saved request: {request}</p>}<dl className="space-y-3 rounded-2xl bg-surface p-4 text-sm"><div><dt className="text-muted">Name</dt><dd>{name || 'Added when you start this service'}</dd></div><div><dt className="text-muted">ID / passport</dt><dd>{identity ? `••••${identity.slice(-4)} · ${status === 'VERIFIED' ? 'Verified' : 'Verification still required'}` : 'We will ask for this'}</dd></div>{province && <div><dt className="text-muted">Province</dt><dd>{province}</dd></div>}{mobile && <div><dt className="text-muted">Contact number</dt><dd>{mobile}</dd></div>}{address && <div><dt className="text-muted">Residential address</dt><dd>{address}</dd></div>}{finances && <div><dt className="text-muted">Last declared monthly income / expenses</dt><dd>{formatZAR(income!)} / {formatZAR(expenses!)}</dd>{date && <p className="mt-1 text-xs text-muted">Last submitted {new Date(date).toLocaleDateString('en-ZA')}</p>}</div>}</dl><label className="flex gap-2 text-sm"><input type="checkbox" checked={reuse} onChange={e => setReuse(e.target.checked)} /><span>These saved details are correct. Ask only for missing details.</span></label>{finances && reuse && <label className="flex gap-2 text-sm"><input type="checkbox" checked={financialCurrent} onChange={e => setFinancialCurrent(e.target.checked)} /><span>I confirm my income and expenses are still accurate for this application.</span></label>}<p className="text-xs text-muted">Uncheck “These saved details are correct” to update your answers. Verified identity changes need support. Draft answers save securely to your account; documents must be attached again if you leave before submitting.</p><Button className="w-full" size="lg" disabled={reuse && finances && !financialCurrent} onClick={onContinue}>{reuse ? 'Confirm & continue' : 'Update my details'}</Button></div>;
}
