// Real HTTP + PostgreSQL semantics in an isolated, in-memory PGlite database.
// Never reads a DATABASE_URL or writes to a deployed database.
console.log('Test: loading API modules');
require('reflect-metadata');
const assert = require('node:assert/strict');
const path = require('node:path');
const { PGlite } = require('@electric-sql/pglite');
const { drizzle } = require('drizzle-orm/pglite');
const { migrate } = require('drizzle-orm/pglite/migrator');
const { eq } = require('drizzle-orm');
const { Test } = require('@nestjs/testing');
const request = require('supertest');
const { makeSaId } = require('@xtra/shared');
process.env.JWT_SECRET = 'isolated-personal-loan-test-secret-32';
process.env.RATE_LIMIT_PER_MIN = '100000';
process.env.DEMO_MODE = 'false';
for (const name of ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'APPLE_CLIENT_ID', 'APPLE_CLIENT_SECRET', 'WHATSAPP_ACCESS_TOKEN', 'IDENTITY_PROVIDER_API_KEY']) delete process.env[name];
const schema = require('../dist/db/schema');
const { AppModule } = require('../dist/app.module');
const { configureApp } = require('../dist/setup');
const { AuthService } = require('../dist/auth/auth.service');
const { encryptIdentity, decryptIdentity, secretHash } = require('../dist/auth/identity-crypto');

async function main() {
  const pg = new PGlite(), db = drizzle(pg, { schema });
  console.log('Test: applying migrations to isolated database');
  await migrate(db, { migrationsFolder: path.join(__dirname, '../drizzle') });
  console.log('Test: booting isolated HTTP application');
  const module = await Test.createTestingModule({ imports: [AppModule] }).overrideProvider('DB_BUNDLE').useValue({ db, pool: { end: () => pg.close() } }).compile();
  const app = module.createNestApplication({ rawBody: true, logger: false });
  configureApp(app); await app.init();
  const http = () => request(app.getHttpServer());
  const bearer = token => ({ Authorization: `Bearer ${token}` });
  try {
    console.log('Test: registration and fixtures');
    const consumer = (await http().post('/auth/register').send({ email: 'applicant@test.invalid', phone: '0820000011', password: 'Passw0rd!', firstName: 'Test', lastName: 'Applicant', accountType: 'CONSUMER' }).expect(201)).body;
    const second = (await http().post('/auth/register').send({ email: 'other@test.invalid', phone: '0820000012', password: 'Passw0rd!', firstName: 'Other', lastName: 'Applicant', accountType: 'CONSUMER' }).expect(201)).body;
    const lender = (await http().post('/auth/register').send({ email: 'lender@test.invalid', phone: '0820000013', password: 'Passw0rd!', firstName: 'Test', lastName: 'Lender', accountType: 'LENDER', lenderName: 'Isolated Lender' }).expect(201)).body;
    const otherLender = (await http().post('/auth/register').send({ email: 'other-lender@test.invalid', phone: '0820000014', password: 'Passw0rd!', firstName: 'Other', lastName: 'Lender', accountType: 'LENDER', lenderName: 'Other Lender' }).expect(201)).body;
    const [admin] = await db.insert(schema.users).values({ email: 'admin@test.invalid', firstName: 'Test', lastName: 'Reviewer', roles: ['ADMIN'], referralCode: 'XCTESTADMIN' }).returning();
    const staff = await app.get(AuthService).issueTokens(admin);
    const [org] = await db.update(schema.lenderOrgs).set({ accreditationStatus: 'ACCREDITED', availableCents: 10000000 }).where(eq(schema.lenderOrgs.ownerUserId, lender.user.id)).returning();
    await db.update(schema.lenderOrgs).set({ accreditationStatus: 'ACCREDITED' }).where(eq(schema.lenderOrgs.ownerUserId, otherLender.user.id));
    const [offer] = await db.insert(schema.loanOffers).values({ lenderId: org.id, productType: 'PERSONAL', name: 'Test Personal', active: true, monthlyInterestRateBps: 100, termMonths: 6, initiationFeeCents: 0, monthlyServiceFeeCents: 0, minAmountCents: 50000, maxAmountPerUserCents: 500000, minMonthlyIncomeCents: 0, minCreditScore: 0, minAge: 18, maxAge: 100, employmentStatuses: [], provinces: [] }).returning();
    const identity = makeSaId(new Date('1990-01-01'), 1234);
    const payload = { amountCents: 100000, termMonths: 6, purpose: 'Transport', monthlyIncomeCents: 1500000, monthlyExpensesCents: 500000, consent: true, idempotencyKey: 'isolated-application-001' };
    console.log('Test: public search, verification and submission');
    const publicResult = await http().post('/personal-loans/precheck').send({ identityType: 'ID', identityNumber: identity, amountCents: payload.amountCents, termMonths: 6, consent: true }).expect(200);
    assert.equal(publicResult.body.potentialOptions, true);
    assert(!JSON.stringify(publicResult.body).includes(org.name)); assert(!JSON.stringify(publicResult.body).includes(identity));
    await http().post('/personal-loans/precheck').send({ identityType: 'ID', identityNumber: '123', consent: true }).expect(400);
    await http().get('/personal-loans/applications').expect(401);
    const locked = await http().post('/personal-loans/matches').set(bearer(consumer.accessToken)).send(payload).expect(200);
    assert.equal(locked.body.locked, true); assert.deepEqual(locked.body.matches, []);
    await http().post('/personal-loans/applications').set(bearer(consumer.accessToken)).send({ ...payload, offerId: offer.id }).expect(400);
    await http().post('/personal-loans/applications').set(bearer(consumer.accessToken)).send({ ...payload, consent: false }).expect(400);
    const initial = await http().post('/personal-loans/applications').set(bearer(consumer.accessToken)).send(payload).expect(201);
    const retries = await Promise.all([1, 2].map(() => http().post('/personal-loans/applications').set(bearer(consumer.accessToken)).send(payload).expect(201)));
    assert(retries.every(r => r.body.id === initial.body.id));
    assert.equal((await http().get('/personal-loans/applications').set(bearer(second.accessToken)).expect(200)).body.length, 0);
    const verifyRequest = () => http().post('/personal-loans/verification').set(bearer(consumer.accessToken)).field('identityType', 'ID').field('identityNumber', identity).field('mobile', '0820000011').field('address', '1 Test Street, Test Town').field('province', 'Gauteng').field('employmentStatus', 'EMPLOYED_FULL_TIME').field('consent', 'true');
    await verifyRequest().attach('identity', Buffer.from('not a pdf'), { filename: 'id.pdf', contentType: 'application/pdf' }).attach('address', Buffer.from('%PDF-1.4 test'), { filename: 'address.pdf', contentType: 'application/pdf' }).expect(400);
    const verification = await verifyRequest().attach('identity', Buffer.from('%PDF-1.4 isolated identity fixture'), { filename: 'id.pdf', contentType: 'application/pdf' }).attach('address', Buffer.from('%PDF-1.4 isolated address fixture'), { filename: 'address.pdf', contentType: 'application/pdf' }).expect(201);
    assert.equal(verification.body.status, 'PENDING'); assert(!JSON.stringify(verification.body).includes(identity));
    await http().get(`/personal-loans/documents/${consumer.user.id}/identity`).set(bearer(second.accessToken)).expect(403);
    await http().get(`/personal-loans/documents/${consumer.user.id}/identity`).set(bearer(lender.accessToken)).expect(403);
    await http().get('/personal-loans/review/applications').set(bearer(consumer.accessToken)).expect(403);
    await http().post(`/personal-loans/review/verification/${consumer.user.id}`).set(bearer(consumer.accessToken)).send({ approve: true }).expect(403);
    await http().post(`/personal-loans/review/verification/${consumer.user.id}`).set(bearer(staff.accessToken)).send({ approve: true }).expect(201);
    const profile = await db.query.kycProfiles.findFirst({ where: eq(schema.kycProfiles.userId, consumer.user.id) });
    assert.equal(profile.creditScore, null); assert.equal(profile.bureauReference, null);
    console.log('Test: lender matching, ownership and review');
    const matched = await http().post('/personal-loans/matches').set(bearer(consumer.accessToken)).send(payload).expect(200);
    assert.equal(matched.body.locked, false); assert.equal(matched.body.matches[0].lenderName, org.name);
    const referred = await http().post('/personal-loans/applications').set(bearer(consumer.accessToken)).send({ ...payload, offerId: offer.id }).expect(201);
    assert.equal(referred.body.id, initial.body.id); assert.equal(referred.body.status, 'REFERRED');
    const replay = await http().post('/personal-loans/applications').set(bearer(consumer.accessToken)).send({ ...payload, amountCents: 50000 }).expect(201);
    assert.equal(replay.body.status, 'REFERRED'); assert.equal(replay.body.amountCents, payload.amountCents);
    assert.equal((await http().get('/lender/personal-applications').set(bearer(otherLender.accessToken)).expect(200)).body.length, 0);
    assert.equal((await http().get('/lender/personal-applications').set(bearer(lender.accessToken)).expect(200)).body.length, 1);
    await http().post(`/personal-loans/applications/${initial.body.id}/review`).set(bearer(otherLender.accessToken)).send({ action: 'REVIEW', notes: 'Test review' }).expect(404);
    await http().post(`/personal-loans/applications/${initial.body.id}/review`).set(bearer(lender.accessToken)).send({ action: 'REVIEW', notes: 'Please supply verified financial information.' }).expect(201);
    const history = await http().get('/personal-loans/applications').set(bearer(consumer.accessToken)).expect(200);
    assert.equal(history.body[0].status, 'UNDER_REVIEW'); assert.equal(history.body[0].reviewNotes, 'Please supply verified financial information.');
    assert.equal((await db.query.loans.findMany()).length, 0); // Applications never create advances.
    const balance = await http().get('/me/balance').set(bearer(consumer.accessToken)).expect(200);
    assert(!JSON.stringify(balance.body.offers).includes(offer.id));
    const config = await http().get('/auth/passwordless/configuration').expect(200);
    assert.equal(config.body.google, false); assert.equal(config.body.whatsapp, false);
    await http().post('/auth/passwordless/whatsapp/send').send({ identityType: 'ID', identityNumber: identity, accountType: 'CONSUMER', consent: true, mobile: '0820000011' }).expect(503);
    await http().post('/lender/offers/assistant').set(bearer(lender.accessToken)).send({ messages: [{ role: 'user', content: `Assess this customer ${identity}` }] }).expect(400);
    const otpPayload = { identityType: 'ID', identityNumber: makeSaId(new Date('1991-01-01'), 4321), accountType: 'CONSUMER', consentAt: new Date().toISOString(), mobile: '+27820000099' };
    const challenge = async secret => (await db.insert(schema.authChallenges).values({ provider: 'whatsapp', secretHash: secretHash(secret + ':unique-' + Math.random()), bindingHash: secretHash(secret), payload: encryptIdentity(JSON.stringify(otpPayload)), expiresAt: new Date(Date.now() + 300000) }).returning())[0];
    const exhausted = await challenge('654321');
    for (let i = 0; i < 5; i++) await http().post('/auth/passwordless/whatsapp/verify').send({ challengeId: exhausted.id, code: '000000' }).expect(401);
    await http().post('/auth/passwordless/whatsapp/verify').send({ challengeId: exhausted.id, code: '654321' }).expect(401);
    const valid = await challenge('654321');
    const login = await http().post('/auth/passwordless/whatsapp/verify').send({ challengeId: valid.id, code: '654321' }).expect(200);
    assert.equal(login.body.user.profileComplete, false); assert.equal(login.body.user.identityEncrypted, undefined);
    await http().get('/me/balance').set(bearer(login.body.accessToken)).expect(403);
    await http().put('/auth/passwordless/profile').set(bearer(login.body.accessToken)).send({ firstName: 'Verified', lastName: 'Test' }).expect(200);
    await http().get('/me/balance').set(bearer(login.body.accessToken)).expect(200);
    await http().post('/auth/passwordless/whatsapp/verify').send({ challengeId: valid.id, code: '654321' }).expect(401);
    const encrypted = encryptIdentity(identity); assert.equal(decryptIdentity(encrypted), identity); assert(!encrypted.includes(identity));
    assert.throws(() => decryptIdentity(encrypted.slice(0, -3) + 'abc')); assert.equal(secretHash(identity), secretHash(identity));
    console.log('PASS: isolated HTTP personal-loan journey, identity lock, document ownership, no fabricated score, idempotency, lender isolation, review updates, no disbursement, provider-unavailable handling and encryption integrity');
  } finally { await app.close(); }
}
main().catch(e => { console.error(e); process.exitCode = 1; });
